### ISSUE TITLE
(question) How would this work on Canadian Market?

### ISSUE THREAD

**Issue by dgomesbr** [tradytics/eiten#1]
On the subject.

Additionally, would one be able to integrate realtime data, plus auto buy/sell?

**Comment by tradytics** [comment]
So for price data, we are currently using yahoo finance since it's free. You can change the data manager file and add your own API for canadian market. Everything else will remain the same so it shouldn't be too hard to do.

As for real time data, there would be other tools to do that but this one was mostly developed for investing purposes and won't really be easily converted into and auto buy sell tool.

Keep this thread open for further discussions.

**Comment by dashed** [comment]
I can confirm Canadian stocks do work. They're suffixed with `.TO` on Yahoo finance. For example: https://ca.finance.yahoo.com/quote/XQQ.TO
