### ISSUE TITLE
Plots not showing; Saving yields a blank png file

### ISSUE THREAD

**Issue by sososasa** [tradytics/eiten#27]
This is all on Google Colab.

I tried showing plot but I get this: 
`<Figure size 1200x600 with 1 Axes>`

So I tried doing:
```
%matplotlib inline
!python portfolio_manager.py --is_test 1 --future_bars 90 --data_granularity_minutes 3600 --history_to_use all --apply_noise_filtering 1 --market_index QQQ --only_long 1 --eigen_portfolio_number 3 --stocks_file_path stocks/stocks.txt
```

But still no output. 

Any ideas why?

**Comment by michaelsutehall** [comment]
Try: 
`python portfolio_manager.py --future_bars 90 --data_granularity_minutes 3600 --history_to_use all --apply_noise_filtering 1 --market_index QQQ --only_long 1 --eigen_portfolio_number 3 --stocks_file_path stocks/stocks.txt`

**Comment by macemoth** [comment]
Instead of running the program with the magic `!python` run it with `%run portfolio_manager.py --is_test 1 ...`. Then, the plots should be displayed correctly.

Source: [stackoverflow.com, Matplotlib plot from Python script not showing up in output when run in Jupyter Notebook](https://stackoverflow.com/questions/57135570/matplotlib-plot-from-python-script-not-showing-up-in-output-when-run-in-jupyter)
